
services:
  mongo_db:
    image: mongo:latest
    container_name: dealerships_db
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  nodeapp:
    image: dealership_review_nodeapp
    container_name: node_app
    ports:
      - "3030:3030"
    depends_on:
      - mongo_db

  django:
    image: djangoapp
    container_name: django_app
    ports:
      - "8000:8000"
    depends_on:
      - nodeapp
      - mongo_db
  sentiment_analyzer:
    image: senti_analyzer  # Replace with your actual image name
    container_name: sentiment_analyzer
    ports:
      - "5001:5000"   # Example port if your analyzer exposes one
    # add volumes, env, etc. as needed

volumes:
  mongo_data: {}
